apiVersion: v2
name: parent1
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
  - name: dep
    version: "0.1.0"
    repository: "file://../dep"
    condition: dep.enabled
